exp:
  config_dir: configs
  config: td_single_ffhq.yaml
  project: Test
  tags:
    - stylespace
  name: Test
  seed: 10
  root: .
  notes: empty notes
  logging: true
  step_save: 20
  trainer: td_single
  epochs: 9
training:
  checkpoint_dir: ./checkpoints_noinput4
  index: 10
  results_save_dir: ./results_cin
  iter_num: 130
  batch_size: 1
  device: cuda:0
  generator: stylegan2
  phase: mapping
  patch_key: cin_mult
  source_class: Face
  domain: Pixar
#  pos_class: high-resolution, high-quanlity, bright, clear, symmetrical Face
  pos_class: real face, realistic,high-resolution, high-quanlity, bright, clear, symmetrical Face
  target_class: Face in the style of Pixar
  neg_class: Rendering, low-resolution, low-quality, dark, blurry, unsymmetrical Face
  auto_layer_k: 10
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.8
render:
  img_size: 512
  topology_path: data/head_template.obj
  dense_topology_path: data/0_detail.obj
  rasterizer_type: pytorch3d
optimization_setup:
  visual_encoders:
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
  loss_coefs:
    - 1.0
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.1
    betas:
    - 0.9
    - 0.999
generator_args:
  albedo_on: False
  checkpoint_path: pretrained/StyleGAN2/stylegan2_ffhq.pt
albedo_args:
  albedo_on: True
  checkpoint_path: pretrained/StyleGAN2/albedo_GAN.pt
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  truncation: 0.7
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 50